variables:
  ulterius_tag: usx
  epiphansdk_tag: epi

stages:
  - build

build-against-ulterius:
  stage: build
  script:
    - mkdir build-%ulterius_tag%
    - cd build-%ulterius_tag%
    - cmake ..
    - cmake --build . --config Release
    - dir
    - dir Release\xono2l-%ulterius_tag%.dll
  tags:
    - gift-hopper

build-against-epiphan-sdk:
  stage: build
  script:
    - mkdir build-%epiphansdk_tag%
    - cd build-%epiphansdk_tag%
    - cmake ..
    - cmake --build . --config Release
    - dir
    - dir Release\xono2l-%epiphansdk_tag%.dll
  tags:
    - gift-hopper
